name: CI - Build, Test, Pack and Publish

on:
  push:
    branches: [ "main", "feature/*" ]
    tags: ["v*"]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    uses: sandre58/MyWorkflows/.github/workflows/ci.yml@main
    with:
      app-projects: "tools"
      nuget-projects: "src"
      app-target-framework: "net10.0"
      test-args:  "--filter \"Category!=Integration\""
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}