name: CI

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write      # required to push to gh-pages
  pages: write         # required to publish to GitHub Pages
  id-token: write      # required for OIDC authentication if needed

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for NBGV

      # Step 2: Set up .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            10.0.x
            9.0.x
            8.0.x

      # Step 3: Restore project dependencies
      - name: Restore
        run: dotnet restore --property:EnableWindowsTargeting=true

      # Step 4: Build the project
      - name: Build
        run: dotnet build --configuration Release --no-restore --property:EnableWindowsTargeting=true

      # Step 5: Run tests and collect code coverage
      - name: Run tests with coverage
        run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage"

      # Step 6: Generate coverage report
      - name: Report coverage
        uses: danielpalme/ReportGenerator-GitHub-Action@v5
        with:
          reports: '**/coverage.cobertura.xml'
          targetdir: 'coverage-report'
          reporttypes: 'Html;Cobertura;MarkdownSummary'

      # Step 7: Upload coverage report as artifact
      - name: Upload coverage report as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./coverage-report

      # Step 8: Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: '**/coverage.cobertura.xml'
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      
      # Step 9: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4