name: Release

on:
  push:
    tags:
      - '*/v*'  # Matches tags like v1.2.3

jobs:
  build:
    uses: sandre58/MyWorkflows/.github/workflows/release.yml@main
    secrets:
      RELEASE_API_KEY: ${{ secrets.NUGET_API_KEY }}
      PRERELEASE_API_KEY: ${{ secrets.GITHUB_TOKEN }}