name: Release

on:
  push:
    tags:
      - 'v*' # ex: v1.2.3

jobs:
  build-test-pack:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            10.0.x
            9.0.x
            8.0.x

      # Step 3: Restore project dependencies
      - name: Restore
        run: dotnet restore --property:EnableWindowsTargeting=true

      # Step 4: Build the project
      - name: Build
        run: dotnet build --configuration Release --no-restore --property:EnableWindowsTargeting=true

      # Step 5: Run tests
      - name: Test
        run: dotnet test --configuration Release --no-build

      # Step 6: Package NuGet artifacts
      - name: Pack NuGet
        run: dotnet pack --configuration Release --no-build --output ./artifacts

      # Step 7: Upload NuGet package as artifact
      - name: Upload NuGet package (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: ./artifacts/*.nupkg

      # Step 8: Push NuGet package to NuGet.org
      - name: Push to NuGet.org
        run: dotnet nuget push "./artifacts/*.nupkg" \
             --source https://api.nuget.org/v3/index.json \
             --api-key ${{ secrets.NUGET_API_KEY }} \
             --skip-duplicate
