name: Release PR

# Trigger the workflow manually
on:
  workflow_dispatch:

jobs:

  release-please:
    runs-on: ubuntu-latest

    steps:

      # Step 1: Run Release Please to automate release and changelog creation
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
